# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter haydn lisa mars odin renoir venus,$(TARGET_DEVICE)),)

endif
